Add authentication service
ostis-ai/sc-server-auth pull request #1
Opened 2022-04-04 11:46 UTC by SHtress

2022-04-05 07:36 UTC, AlexandrZagorskiy requested changes

2022-04-05 07:36 UTC, AlexandrZagorskiy commented on requirements.txt
> +jwt
change to PyJWT

2022-04-05 07:36 UTC, AlexandrZagorskiy commented on requirements.txt
> +
Add uvicorn

2022-04-05 07:36 UTC, AlexandrZagorskiy commented on requirements.txt
> +
I think better to add poetry to project

2022-04-05 07:36 UTC, AlexandrZagorskiy commented on README.md
> +
Update readme

2022-04-05 07:36 UTC, AlexandrZagorskiy commented on admin.py
> +    print(user_info)
remove prints, or change to loggings

2022-04-05 07:36 UTC, AlexandrZagorskiy commented on admin.py
> +    sc_response = requests.post(url="http://127.0.0.1:8090/admin/user", json=user_info).json()
move main url with routes to config file. I will send you example of config file from another project

2022-04-05 07:36 UTC, AlexandrZagorskiy commented on auth.py
> +    pkey.generate_key(type=crypto.TYPE_RSA, bits=2048)
move "2048" to constants

2022-04-06 08:59 UTC, AlexandrZagorskiy requested changes

2022-04-06 08:59 UTC, AlexandrZagorskiy commented on run_server.sh
> +   echo "c     port of a platform sc-server(default value is 8090)"
remove unused args from script, update --help info

2022-04-08 08:17 UTC, AlexandrZagorskiy requested changes

2022-04-08 08:17 UTC, AlexandrZagorskiy commented on constants.py
> +WS_JSON_URL = 'ws://localhost:8090/ws_json' #TODO Add dynamic generation for url
move to config, and use existed constants

2022-04-08 08:17 UTC, AlexandrZagorskiy commented on admin.py
> +async def generate_user_args(user_info):
why async?

2022-04-08 08:17 UTC, AlexandrZagorskiy commented on admin.py
> +    return const
You can skip return statement here

2022-04-08 08:17 UTC, AlexandrZagorskiy commented on admin.py
> +async def generate_user_args(user_info):
Also review typing in new functions

2022-05-19 11:46 UTC, FallenChromium commented on sc-server-auth/server/server_tests.py
> +wrong_pass_creds = {"name": "admin", "password": "a665a45923422f9d417e5867efdc4fb8a06a1f3fff1fa07e998e86f7f7a27ae3"}
I'm not quite sure why `user_creds` password and `wrong_pass_creds` password are same - is it intended?

2022-05-19 11:46 UTC, FallenChromium commented on sc-server-auth/server/admin.py
> +    elif len(password.strip()) == 0:
That doesn't look right to me. Perhaps we could move password validation to a separate function and, while we're at it, create some additional requirements for the password (no non-latin characters, some minimal length, etc.)

2022-05-19 12:40 UTC, SHtress commented on sc-server-auth/server/server_tests.py
> +wrong_pass_creds = {"name": "admin", "password": "a665a45923422f9d417e5867efdc4fb8a06a1f3fff1fa07e998e86f7f7a27ae3"}
Test will be changed latter, not so important for now

2022-05-19 12:41 UTC, SHtress commented on sc-server-auth/server/admin.py
> +    elif len(password.strip()) == 0:
Yes it's good idea, we will think about later, but now we need working version without creating and deleting users

2022-05-19 12:44 UTC, AlexandrZagorskiy approved these changes

2022-05-19 15:38 UTC, merged