Google token endpoint
ostis-ai/sc-server-auth pull request #11
Opened 2022-07-26 08:18 UTC by KernTHeAce

Endpoint for google auth

2022-07-26 11:10 UTC, FalseR20 requested changes
And rmove empty file sc_server_auth/config,py

2022-07-26 11:10 UTC, FalseR20 commented on pyproject.toml
> +google-auth-oauthlib = "^0.5.2"
I think you either add it to the end or sort all dependencies

2022-07-26 11:10 UTC, FalseR20 commented on sc_server_auth/__main__.py
> +        "-g", "--google-secret", help=f"Path to google client secret (default: {args.google_secret})", type=str
I think you can use type Path like above

2022-07-26 11:10 UTC, FalseR20 commented on sc_server_auth/configs/constants.py
> +PUBLIC_KEY_PATH = "public_key"
SQLITE_DB_PATH, PRIVATE_KEY_PATH and PUBLIC_KEY_PATH are in file config/paths, so remove they

2022-07-26 11:10 UTC, FalseR20 commented on sc_server_auth/configs/settings.toml
> +google_secret = ""
I think you can add default value

2022-07-26 11:10 UTC, FalseR20 commented on sc_server_auth/configs/models.py
> +    google_local_server_port: int
Maybe create a separate dataclass for this?

2022-07-26 11:10 UTC, FalseR20 commented on sc_server_auth/configs/models.py
> +    google_secret: str = None
I think it's better to rename:
```python
google_secret_path: Path = None
```

2022-07-27 13:32 UTC, FalseR20 requested changes

2022-07-27 13:32 UTC, FalseR20 commented on sc_server_auth/configs/settings.toml
> +
This line disturbs the world balance

2022-07-27 13:32 UTC, FalseR20 commented on README.md
> +python3 -m sc_server_auth [-h] [-H HOST] [-p PORT] [-d DATABASE] [-l LOG_LEVEL] [-r] [-e DOT_ENV] [-g GOOGLE_SECRET_FILE_PATH]
Add part about google secret

2022-07-28 13:57 UTC, FalseR20 approved these changes

2022-07-28 13:57 UTC, FalseR20 commented on README.md
> +Giting client_secret.json file [tutorial](https://help.talend.com/r/en-US/7.2/google-drive/how-to-access-google-drive-using-client-secret-json-file-the)
Maybe "Getting"? Also add something like "or ask colleagues" and about default place

2022-07-28 13:57 UTC, FalseR20 commented on README.md
> +python -m sc_server_auth [-h] [-H HOST] [-p PORT] [-d DATABASE] [-l LOG_LEVEL] [-r] [-e DOT_ENV] [-g GOOGLE_SECRET_FILE_PATH]
If you change python3 on python, change it in help usage

2022-07-28 14:20 UTC, kroschenko requested changes

2022-07-28 14:20 UTC, kroschenko commented on sc_server_auth/configs/settings.toml
> +
delete this line

2022-07-28 14:20 UTC, kroschenko commented on sc_server_auth/server/auth.py
> +        flow = InstalledAppFlow.from_client_secrets_file(google_config.secret_path, [google_config.scope])
Maybe it will be better use str(google_config.secret_path) instead

2022-07-28 14:20 UTC, kroschenko commented on sc_server_auth/configs/parser.py
> +print(type(get_config().google.secret_path))
Please, delete console spam

2022-07-28 14:41 UTC, kroschenko requested changes

2022-07-28 14:41 UTC, kroschenko commented on README.md
> +Giting client_secret.json file [tutorial](https://help.talend.com/r/en-US/7.2/google-drive/how-to-access-google-drive-using-client-secret-json-file-the)
Ok, I got a secret file from Google via Credentials -> OAuth 2.0 Client IDs (after create an application - I am not sure that it is a correct way). I typed it as a param while running a server, and opened page 127.0.0.1:5000/docs. After that I get a token through auth/get_google_token. How do I check this new token?

2022-07-29 10:37 UTC, kroschenko approved these changes

2022-07-29 10:50 UTC, merged