Add PostgreSQL
ostis-ai/sc-server-auth pull request #6
Opened 2022-07-13 11:12 UTC by FalseR20

# How to test locally:
**Preparations:**
- poetry install
- create database in postgres as in readme
- change database system in [config.py](https://github.com/FalseR20/sc-server-auth/blob/feature/add_postgres/sc_server_auth/config.py#:~:text=%3A%20Database.-,SQLITE,-%2C%20%20%23%20Change%20database)
- run [database_default_insert.sql](https://github.com/FalseR20/sc-server-auth/blob/feature/add_postgres/database_default_insert.sql) in pycharm

**Testing:**
- local ci
- run server

2022-07-19 14:07 UTC, AlexandrZagorskiy requested changes

2022-07-19 14:07 UTC, AlexandrZagorskiy commented on sc_server_auth/server/database.py
> +#     users = relationship(cnt.USER)
please remove comments

2022-07-19 14:07 UTC, AlexandrZagorskiy commented on sc_server_auth/server/database.py
> -    def init(self) -> None:
why you decide to delete init function? Is your connection to postgres didn't break the logic?

2022-07-19 14:07 UTC, AlexandrZagorskiy commented on README.md
> +Run `database_default_insert.sql` in pycharm  <!--- temporally -->
Can you make a script which will execute this code automatically? Also I didn't like that you mention pycharm here, can you remove it?

2022-07-20 09:08 UTC, FalseR20 commented on sc_server_auth/server/database.py
> -    def init(self) -> None:
def init() was not used and table was not created. I connected __init__ and init without breaking the logic

2022-07-20 09:08 UTC, FalseR20 commented on sc_server_auth/server/database.py
> +#     users = relationship(cnt.USER)
done

2022-07-20 09:08 UTC, FalseR20 commented on README.md
> +Run `database_default_insert.sql` in pycharm  <!--- temporally -->
It will be in readme

2022-07-20 13:30 UTC, AlexandrZagorskiy approved these changes

2022-07-21 08:49 UTC, merged