Google token
ostis-ai/sc-server-auth pull request #7
Opened 2022-07-21 08:40 UTC by KernTHeAce

2022-07-21 20:55 UTC, AlexandrZagorskiy requested changes
Let's firstly merge #8, and then you will rebase and refactor your code with new codestyle

2022-07-21 20:55 UTC, AlexandrZagorskiy commented on sc_server_auth/config.py
> +    cnt.GOOGLE_CLIENT_SECRET: "sc_server_auth/client_secret.json",
Where should I get this secret? I think this argument should be configurable, and also you should provide the ability to pass secret path as an argument of a server running script

2022-07-21 20:55 UTC, AlexandrZagorskiy commented on sc_server_auth/server/auth.py
> +        params[cnt.GOOGLE_CLIENT_SECRET], ["https://www.googleapis.com/auth/userinfo.profile"]
move this url to constants

2022-07-21 20:55 UTC, AlexandrZagorskiy commented on sc_server_auth/server/auth.py
> +    creds = flow.run_local_server(port=0)
why port always will be 0? Should I change this value sometimes, or not?

2022-07-21 20:55 UTC, AlexandrZagorskiy commented on sc_server_auth/server/models.py
> +    if len(value) > 800:
what is 800? Move it to constants

2022-07-26 10:36 UTC, KernTHeAce commented
Rebase problem: a lot of commits from develop moved to this branch. There is new PR and commits moved to new brunch with cherry-pick

2022-07-26 10:36 UTC, closed without merging