Sort imports script
ostis-ai/sc-server-auth pull request #9
Opened 2022-07-21 11:03 UTC by FalseR20

2022-07-21 18:02 UTC, AlexandrZagorskiy requested changes

2022-07-21 18:02 UTC, AlexandrZagorskiy commented on scripts/sort_imports.sh
> +  poetry run isort -l 120 sc_server_auth/
What about _tests_ directory?

2022-07-21 18:15 UTC, FalseR20 commented on scripts/sort_imports.sh
> +  poetry run isort -l 120 sc_server_auth/
no problem

2022-07-25 12:50 UTC, FalseR20 commented on scripts/sort_imports.sh
> +  poetry run isort -l 120 sc_server_auth/
Yeah, it works there correctly

2022-07-25 13:13 UTC, AlexandrZagorskiy approved these changes

2022-07-25 13:37 UTC, merged